# Generated by Django 5.0.6 on 2024-06-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
